### ISSUE TITLE
Filter out some tracking

### ISSUE THREAD

**Issue by Mobilpadde** [mikecao/umami#1027]
I simply love Umami! It's great, simple design and all.

One thing I've been wondering though, is it possible to filter out all tracking of `localhost`? It annoys me that it's in my stats :dagger:

Would be a great addition! :100:

**Comment by Sammy-T** [comment]
I think something like this, if implemented, might be an optional parameter. Could you provide more info on your use case?

In my case, I haven't found it to be much of an issue since the stats can be useful for my local dev installation. For my live sites, I either make sure to only build with the tracking script on production or I can inject the script as a snippet when pushing to my Netlify hosted sites.

**Comment by Sammy-T** [comment]
Actually, I totally forgot that there's the `data-domains` property which sets which domains to track. That should be what you're looking for.
https://umami.is/docs/tracker-config

**Comment by Mobilpadde** [comment]
Great, that's exactly what I need! Thanks! :partying_face:

**Comment by Mobilpadde** [comment]
Sadly I've tried using `data-domains` and still no success?

**Comment by mikecao** [comment]
@Mobilpadde what is not working? The `data-domains` matches against `window.location.hostname`. Are those values the same?

**Comment by Mobilpadde** [comment]
I'm matching againt `data-domains="hasty.dev,embed.hasty.dev"` so two domains in the exact same way as the docs, and what `window.location.hostname` gives, sadly I'm still getting localhost in my stats :cry:

**Comment by mikecao** [comment]
You can also set `umami.disabled` to true in local storage when you're using localhost.
