### ISSUE TITLE
Query regarding unique visitor count 

### ISSUE THREAD

**Issue by snghneha** [mikecao/umami#1099]
How does umami identify a unique user/visitor ? 
Is it browser specific ? 
When a different user (new login)  logs in to the website via the same browser, using the same machine/computer, there is no change in visitor count i.e. there is no new entry in the session table.

Is this the correct behaviour ?

**Comment by mikecao** [comment]
```
const session_uuid = uuid(website_id, hostname, ip, userAgent);
```
This is how session ids are calculated. A session is a unique visitor. If they change any of those variables they are considered a different user.

**Comment by hugohjerten** [comment]
@mikecao I'm trying to go through the source code to understand where/how the different metrics are calculated, for example the `session_uuid` that you mention above. Could you point me to the right direction? I would like to understand if a unique user is considered unique across the entire time period, or per day.

**Comment by deltatree** [comment]
const sessionId = uuid(websiteId, hostname, ip, userAgent);
Quelle: https://github.com/umami-software/umami/blob/784237bfab6da8c960efac7fd1073b8e0f67dfd9/src/lib/session.ts#L69

**Comment by deltatree** [comment]
Using an IP address as part of a unique ID is not a good idea due to several factors that obscure or change the IP address, making it unreliable for consistent identification:

1. **VPNs and Proxies**: These services hide the real IP address and display a different one, often from a different location.

2. **Network Address Translation (NAT)**: Multiple devices share a single public IP address, hiding individual internal IPs.

3. **IPv6 Adoption**: The vast number of addresses in IPv6 complicates tracking individual IPs.

4. **Cloud Services and Load Balancers**: These can alter or mask the original source IP.

5. **Data Privacy Regulations**: Laws like the GDPR restrict how IPs, as personal data, can be used.

6. **The Tor Network**: This network routes traffic through several servers, heavily anonymizing the source IP.

7. **Content Delivery Networks (CDNs)**: CDNs, acting as proxies, can obscure the user's actual IP.

8. **Dynamic IP Addresses**: These frequently changing addresses make it hard to track a user consistently.

These factors collectively hinder the reliability of using an IP address as a unique identifier in today's internet landscape.

**Comment by pinkli** [comment]
Is it ok to remove the `hostname` from session_id calculation? for a website consisting of multiple subdomains interlinked together, a actual visitor will be counted multiple times.

**Comment by mikaello** [comment]
When https://github.com/umami-software/umami/pull/3334 is released, a new prop `id` will also be taken into account to determine unique visitor count.
