### ISSUE TITLE
Installed application, but no data!

### ISSUE THREAD

**Issue by pefman** [mikecao/umami#114]
Hey there!

I just installed the application using the docker method, everything seems to install smooth. I can access the admin interface.
If i manually go to the .js script its correctly loaded however i receive no data on the websites i have added.

Is there any form of debugging i can use?

Its seems like data is not dumped correctly into the database.

**Comment by mikecao** [comment]
Open up the browser devtools and check the Network tab. You should see a bunch of `/api/collect` calls on your website. Make sure they aren't returning errors.

**Comment by pefman** [comment]
> Open up the browser devtools and check the Network tab. You should see a bunch of `/api/collect` calls on your website. Make sure they aren't returning errors.

Thanks for your quick response! I cant find any errors, but when i checked the database it seems like its empty! :(

**Comment by pefman** [comment]
I think i found the issue. site wont include the javascript, becuase its hosted on http not https and are giving mixed content.

**Comment by joshinat0r** [comment]
Someone had a similar issue here: https://github.com/mikecao/umami/issues/91#issuecomment-685451847

Routing the public umami endpoints (the `umami.js` file and `/api/collect` ) within your server to the https URL should do the trick if you have access to that nginx/apache config.
The browser never knows about the http because externally its all the same domain (which would also bypasses some of the regex-tests for `^stats.*` or `^tracker.*` that some blockers use)

**Comment by pefman** [comment]
The issue for me was that https sites would not allow the script to be loaded from http, causing mixed content so that the .js file was ignored. Running umami and js agent on https solved it :-)
