### ISSUE TITLE
Export data as CSV

### ISSUE THREAD

**Issue by SigmundurMorkore** [mikecao/umami#310]
Would it be possible to add a button on the dashboard to export a website's data as a CSV?

**Comment by mikecao** [comment]
Not sure how valuable it would be since you already have all the data. But if someone wants to explore some options and submit a PR I'll take a look.

**Comment by SigmundurMorkore** [comment]
Sorry for the late response. I think a export option would be beneficial to

* allow for more "manual" analysis of the data.
* And to prevent the data being locked into umami, and making it easier to switch to another service if the user wishes, without losing all the data gathered by umami.

I'm not sure how this could be implemented though.

**Comment by mikecao** [comment]
Well the data is not locked because it's your database. You can simply do a `mysqldump` or `pg_dump` of your database and import that directly into Excel. Even if we were to add a CSV option, it would have to be aggregate data for performance reasons. You can't simply pull an entire year's worth of data over the web.

**Comment by binyamin** [comment]
@mikecao re https://github.com/mikecao/umami/issues/310#issuecomment-714289694 can you put a note in the docs, about the data dump? That would be very helpful.
