### ISSUE TITLE
SameSite issue

### ISSUE THREAD

**Issue by vvo** [mikecao/umami#32]
Hi there, on Google Chrome here's what I am getting when trying to use umami:

```
A cookie associated with a cross-site resource at [redacted] was set without the `SameSite` attribute. 

It has been blocked, as Chrome now only delivers cookies with cross-site requests if they are set with `SameSite=None` and `Secure`.

You can review cookies in developer tools under Application>Storage>Cookies and see more details at 

https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.
```

Example website: https://nextjsnews.com

I believe we should explicitly set the SameSite attribute on the umami cookie, not sure which value, do you know? More at https://web.dev/samesite-cookies-explained/

Chrome version: 84.0.4147.125

**Comment by ivylee** [comment]
Seeing the same issue on Firefox
```
Cookie “umami.auth” will be soon rejected because it has the “sameSite” attribute set to “none” or an invalid value, without the “secure” attribute. To know more about the “sameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite
```

**Comment by mikecao** [comment]
Fixed here 343e59e6ff0b40057902a641bbe9957107e2f293

**Comment by vvo** [comment]
Thanks @mikecao, can you explain briefly how it works? By setting sameSite true, it sets a "strict" policy and I wonder how it can work to track referrers etc for example? 
![image](https://user-images.githubusercontent.com/123822/90815695-61ac4480-e32b-11ea-979d-01f7b033aee8.png)

(From https://web.dev/samesite-cookies-explained/)

thanks in advance

**Comment by mikecao** [comment]
The cookie doesn't do any tracking, it's just the login cookie for your umami app. Assume you have two sites, my-umami.com and my-website.com. Since my-website.com has a tracking code that points to my-umami.com, the cookie is sent along as well. But since you are on a different site than my-umami.com at the time, the browser complains. Setting the SameSite attribute just tells the browser to only send the cookie if you are actually on my-umami.com and nowhere else.

**Comment by vvo** [comment]
👍 thanks!
