### ISSUE TITLE
Make login page responsive 

### ISSUE THREAD

**Issue by CamTosh** [mikecao/umami#326]

**Comment by mikecao** [comment]
What do you mean, is it not responsive now?

**Comment by CamTosh** [comment]
![Screenshot_20201022-092143__01](https://user-images.githubusercontent.com/4854563/96838605-5d45fa00-1448-11eb-8d9b-136148e5aae5.jpg)

Hey, i have some issues with my phone. OnePlus 6T

**Comment by mikecao** [comment]
I see, the error message is off screen. Ok will fix.

**Comment by CamTosh** [comment]
thank's :)

**Comment by arnellebalane** [comment]
Hi @mikecao , I'd like to help fix this issue with the error message going offscreen. I did a quick experiment on one way to handle this, do you think placing the error message below the input field (instead of in an absolutely-positioned tooltip) when on narrow screen widths (<= 576px, the smallest breakpoint I could find being used in the app) is okay? It would look something like this:

![image](https://user-images.githubusercontent.com/1428598/96890588-5ce64700-14ba-11eb-9303-279656947b82.png)

Please let us know also if you already have something in mind on how you'd like the error message to be handled! 😄

**Comment by mikecao** [comment]
@arnellebalane I think we can use the same tooltip component, just have it render below instead of to the side. I believe it's already absolutely positioned and just need some tweaking of css.

**Comment by arnellebalane** [comment]
@mikecao Something like this? 

![image](https://user-images.githubusercontent.com/1428598/96893618-7b9a0d00-14bd-11eb-8ba4-3d347aad8657.png)

**Comment by mikecao** [comment]
Yes 👍

**Comment by arnellebalane** [comment]
Got it, I'll do it this way, thanks for your inputs @mikecao ! 👍

**Comment by mikecao** [comment]
Fixed in #337
