### ISSUE TITLE
[Security] Protect share links

### ISSUE THREAD

**Issue by elMor3no** [mikecao/umami#385]
It would be very helpful to add the possibility to choose if the shared link is public or only for some previously registered users.

I do not think public access to statistics is convenient

**Comment by patrickxchong** [comment]
I agree! A password to protect the shared link, or a way for logged in Umami accounts to access the data of a site would be good.

**Comment by MoltenCoffee** [comment]
I agree fully public statistics don't really serve a purpose for most websites. However, when protecting the shared URL with a password, would it really be any different than creating an account?

A use case I personally could imagine, is when you have an existing web app with login and whatnot, and you'd embed the statistics in there for certain users or user groups, the main purpose being users don't need to access a separate URL for something and/or could access both the app and the statistics with the same credentials. That could get complicated quickly though, especially when designing it in an infrastructure-agnostic way.

**Comment by mikecao** [comment]
I decided early on that I didn't a complex permissions system for the app. The primary use case is for users to self-host stats for their own websites. Having other user accounts is the rare use case. The public url is supposed to solve the issue of sharing stats with others. It's protected simply by being random. The only people who have access are the people you give the url out to in the first place.

I only marked this as an enhancement because I thought maybe we could add password protection. But now that I think about it, it's not any different from someone sharing the password as well. Restricting to only registered user accounts is only extra overhead to accomplish the same thing as the share link.

**Comment by adudeongithub** [comment]
I don't think a password is necessary considering the randomness of the URLs generated. However, it'd be nice to be able to set the share links as valid for X amount of time in hours and/or days. I'm currently talking to a prospective advertiser and may use this feature to share my stats; it would be reassuring to know they can only access the information for so long.
