### ISSUE TITLE
What is the "application startup file"?

### ISSUE THREAD

**Issue by JoshuaLindquist** [mikecao/umami#418]
I am trying to set up Umami on shared hosting with cPanel. It has been frustrating, to say the least, but I think I have everything working now except for one detail. 

The cPanel GUI insists that I provide the "application startup file" in a form field.

This defaults to an automatically generated JS file that just prints "it works" and the Node version on the screen. So, my assumption is that I need to give it the path to whatever file should be loaded initially when starting Umami. 

Can anyone provide this information?

Edit: Upon further research, this problem seems to be related to Issue #360. I thought I had solved that issue, but apparently not.

**Comment by meirroth** [comment]
Hi @JoshuaLindquist,
Have you successfully manged to install and run Umami on a shared server?
I have tried multiple times and I didn't get it to work so I gave up... that's the reason I closed issue #360.
My guess is that its not working because there isn't swap memory on my shared server, but I don't really know.
I would really appreciate your input here, if it worked for you.
Thanks
