### ISSUE TITLE
Feature request: EU time and date format?

### ISSUE THREAD

**Issue by NoLooseEnds** [mikecao/umami#483]
I just noticed that it's only US date format (even if you select another language):

<img width="1090" alt="Screenshot 2021-02-18 at 09 33 59" src="https://user-images.githubusercontent.com/4103531/108328056-70858e00-71cc-11eb-8c23-916e04ab06d2.png">

The correct would be reversing the month and day:
Sun 14/2, Mon 15/2, etc.

Also 24h clock, instead of AM/PM
<img width="1055" alt="Screenshot 2021-02-18 at 09 35 33" src="https://user-images.githubusercontent.com/4103531/108328248-a9256780-71cc-11eb-81e6-5de31c4c542c.png">

Not really a big issue, but always nice to have, and would make an already great tool a little bit better. :)

**Comment by andlil** [comment]
Yes please! #193

**Comment by MoltenCoffee** [comment]
I actually looked into this some time ago, but eventually didn't submit a PR.

Under the hood, the `format()` function from `date-fns` is used to format these things. This works quite well, but in the way it's used right now, causes problems with different format like in this instance.

The `format()` function[ takes a string representing the format](https://date-fns.org/v1.9.0/docs/format) as a parameter. This is hardcoded to `ha`, with `h` being hours on a 12-hour clock and `a` being am/pm.

To fix this, what I did back then was adding another object in `/lib/lang.js`, with the `format` strings for different locales, and creating a slightly altered copy of `dateFormat()` in the same file:

```js
export const timeFormats = {
  'en-US': 'ha',
  'nl-NL': 'H',
  ...
}

export function timeFormat(date, locale) {
  return format(date, timeFormats[locale] || 'ha', { locale: dateLocales[locale] || enUS });
}
```

This function could then be called instead of `dateFormat()` in `compoonents/metrics/BarChart.js`.

I didn't think of it as such an elegant solution, so I decided against submitting a PR. One of the main problems I saw was that the X-axis would now just be a row of numbers. I think most people would recognize it as being hours on a clock, but without the AM/PM it sort of looked 'off' to me.

**Comment by NoLooseEnds** [comment]
To solve the weirdness you could just add `:00` i.e 12:00 … 17:00 … 23:00, etc. (or "12h … 17h … 23h" – my favorite is the first).

**Comment by MoltenCoffee** [comment]
> To solve the weirdness you could just add `:00` i.e 12:00 … 17:00 … 23:00, etc. (or "12h … 17h … 23h" – my favorite is the first).

Well, the thing is that that will prove much more work than 'just' adding `:00`, as that's not an option in the date-fns `format()` function, which will mean you'd have to add extra logic for every locale that might have a different preferred way of showing this.

**Comment by NoLooseEnds** [comment]
I'm not a "proper" developer, so I'm out of my comfort zone, but would adding `"HH':00'"` work? (ref. the examples at the bottom of https://date-fns.org/v2.17.0/docs/format)

Alternatively `"HH':'mm"`, but that would maybe cause that you get the exact minute (i.e 13:17, instead of 13:00)

**Comment by MoltenCoffee** [comment]
@NoLooseEnds you're right!

I tried some things, and turns out the following is indeed possible (just to give some examples):

```
export const timeFormats = {
  'en-US': 'ha',
  'nl-NL': "H:00",
  'de-DE': "H 'Uhr'",
  ...
}
`

**Comment by MoltenCoffee** [comment]
@mikecao what's your opinion on this? Do you have better ideas perhaps? 

I just noticed there's also a `p` format option, 'Long localized time'. This is `12:00` for most languages, but `12:00 PM` in English for example. This is slightly less clean than the `12PM` it shows atm. I also noticed this longer format will cause uneven times to be hidden on the x-axis on certain screens, because of lack of space.

This `p` could be a nice default value, and then use the method described above for exceptions, such as using `ha` for en-US.

**Comment by mikecao** [comment]
What I've generally tried to do is choose a format that "looks nice" for en-US. But I think having custom formats for other locales with default fallback to en-US could work.
