### ISSUE TITLE
[Feature Request] don't track users with auth cookie

### ISSUE THREAD

**Issue by raphael-sch** [mikecao/umami#654]
A setting to not track users that have the appropriate umami.auth cookie would be helpful to ignore traffic from the administrator. IGNORE_IP is only semi helpful if you access your own website with a dynamic IP or different devices.

**Comment by foxytocin** [comment]
Generally a good idea. But that could only work if umami and the tracked website correspond to the same domain. Otherwise, cross-domain-cookies must be used so that the tracked website can read the umami site's cookie to check agains _umami.auth_. This may violate the privacy that umami is supposed to achieve.

**Comment by foxytocin** [comment]
@raphael-sch Right now you can use localeStorage to set an 'DoNotTack-Item'. On the page on which you do not want to be tracked, simply create a localStorage item by running the following line in console of the browser and refresh the page afterwards.

`localStorage.setItem('umami.disabled', true);`

**Comment by mikecao** [comment]
☝️ the solution by @foxytocin is the right one

**Comment by xerod** [comment]
> @raphael-sch Right now you can use localeStorage to set an 'DoNotTack-Item'. On the page on which you do not want to be tracked, simply create a localStorage item by running the following line in console of the browser and refresh the page afterwards.
> 
> `localStorage.setItem('umami.disabled', true);`

this should be included in the docs
