### ISSUE TITLE
[Feature] Set ignore IP on admin panel

### ISSUE THREAD

**Issue by babeuloula** [mikecao/umami#703]
Hello,

I use UptimeRobot on my websites and they have so much IP. You think it's a good idea to set IP on admin panel instead of environment variable ?

UptimeRobot IP list : https://uptimerobot.com/inc/files/ips/IPv4andIPv6.txt

Thanks

**Comment by joshinat0r** [comment]
Does uptimerobot even appear in your statistics?
Assuming they execute JS (no idea if they do), they appear in [user-agents.net](https://user-agents.net/bots/uptimerobot) and [isbot()](https://github.com/mikecao/umami/blob/master/pages/api/collect.js#L12) checks against that already.
So the bot detection should kick in and not count towards your stats.

On another note, don't see why you would want to add 50+ entries via the admin UI.
You could write a bash script that reads their TXT, joins them with `,` and uses that as the enviornment variable when you start your container. Not just quicker initially but also once they change their IPs.
Automation is the reason why they publish a txt that's easily processable.

**Comment by babeuloula** [comment]
I don't know if it's uptimerobot or an other bot but I've got several visit with <1s and my bounce rate increase.
You have any logs ?

**Comment by joshinat0r** [comment]
I'm using Grafana and curl to check my uptime, so I don't use uptimerobot on my sites.
Just saying that if `collect.js` is working correctly then uptimerobot gets already filtered out because `isbot` flags it as a bot.
And from a quick test by using `Mozilla/5.0 (compatible; UptimeRobot/2.0; http://www.uptimerobot.com/)` in my browser as UA seems to work just fine, every pageview and event while faking my useragent does not appear in the realtime dashboard.

Umami has no heartbeat, so you should take the visit duration with a grain of salt anyways.
If a user is landing on `/foo`, reads the page for 15mins and quits the page then Umami has no idea how long the user was on that page. The `average visit time` can only work if there are two datapoints. We get that 2nd datapoint when the user navigates to `/bar`, but once the user is navigating to a second page it's not a bounce anymore.
So "1s visits and bouncerate increase" don't necessarily mean that it's a bot.

**Comment by mikecao** [comment]
@joshinat0r is correct. Bounce rate has no bearing on whether the user is a bot or not. Bots should be filtered out by the `is-bot` package. If they are spoofing the user-agent, then there's nothing we can do really.
