### ISSUE TITLE
[question] How does this app fit with GDPR

### ISSUE THREAD

**Issue by djrasmusp** [mikecao/umami#76]
Hey,

First of Mike, brilliant app...

But how does this app fit with GDPR ? Can it be used without detailing it in the cookie compliance or would it be similar to, if google analystic was used ?

**Comment by mikecao** [comment]
It should be GDPR compliant. It doesn't use any cookies and all data is anonymized so you can't trace it back to any particular user. Umami uses the same techniques as other products that claim to be GDPR compliant, but since I'm not a lawyer I didn't want to make any such claims.

**Comment by mikecao** [comment]
Closing as answered.

**Comment by david-mears-2** [comment]
Developers in the UK should note that, at least in 2025,

> You must obtain consent for:  [...] tracking or profiling individual visitors or categories of visitors (eg based on their IP address or the pages they visited on your website).

https://ico.org.uk/for-organisations/direct-marketing-and-privacy-and-electronic-communications/guidance-on-the-use-of-storage-and-access-technologies/what-are-the-exceptions/#statistical

Since umami fingerprints users by ID + device + browser and only cycles the id every month (as per docs https://umami.is/docs/metric-definitions#location-metrics and implemented [here](https://github.com/umami-software/umami/blob/2260520ae58b7b79327f0f50e4d465931b07f41c/src/app/api/send/route.ts#L133)), it would count as tracking individual visitors. Indeed, umami's docs [talk about tracking the number of visitors](https://umami.is/docs/metric-definitions#location-metrics) in addition to visits, and advertise a 'retention' report feature, so we're definitely in the realm of "tracking or profiling individual visitors". Comparable analytics solutions use shorter salt rotation periods in order to avoid tracking individual visitors: e.g. 24 hours for Fathom, 24 hours for Posthog, 8 hours for goatcounter. These are more fairly described as tracking _sessions_ or _visits_ as opposed to visitors.

There is currently no way to disable this tracking of unique visitors (see https://github.com/umami-software/umami/issues/4031, https://github.com/umami-software/umami/issues/4033). So user consent would be required to use umami in the UK jurisdiction.

Umami is only UK GDPR compliant if your site obtains user consent before running any umami scripts.
