### ISSUE TITLE
Data not being collected

### ISSUE THREAD

**Issue by Sitio-web-dk** [mikecao/umami#91]
Does ssl need to be activated for the dashboard domain to collect data?

At the moment, the javascript file is not being loading.

<img width="95" alt="error" src="https://user-images.githubusercontent.com/64963105/91942113-a5735680-ecfa-11ea-87d5-1b336cef7ee3.png">

**Comment by joshinat0r** [comment]
It shouldn't really matter if SSL is enabled or disabled, at least for Umami itself.

[The snippet you're getting from the dashboard](https://github.com/mikecao/umami/blob/bf6df3647a6538832874231d0293bcca43fa7cc5/components/forms/TrackingCodeForm.js#L21) is using the browsers URL, so if you open the dashboard via `http://...` it'll generate a `src='http://'` snippet.

[The tracker](https://github.com/mikecao/umami/blob/master/tracker/index.js#L22) itself also doesn't care about it, it's using the `data-host-url` attribute from the script-tag if available, otherwise it's using the domain from the scripts src attribute.


What is exact error message from your screenshot?
I would guess it's a mixed content warning, browsers tend to not like it when you load stuff from http while the site itself is https. Mixed content pictures usually just throw a warning in the console, but loading JS over http can lead to MITM attacks on your site.

____
**If** there is a good reason not to have Umami running on https and you have access to the nginx/apache config then you could try and reverse proxy all Umami-tracking through your https-site.

My site has those two blocks in nginx, and is then forwarding all the user-facing umami-stuff internally to my docker container.
So the users browser is loading `example.com/umami.js` and API calls go to `example.com/api/collect` and nginx is proxying it to the container internally.
Which means the browser doesn't know there is a `umami.example.com` url and wouldn't care that it's not http.
The dashboard itself should work just fine if everything is served via http.
```
        location /umami.js {
                proxy_pass http://127.0.0.1:3000;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
        }

        .....

        location /api/collect {
                proxy_pass http://127.0.0.1:3000;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
        }
```

**Comment by mikecao** [comment]
Closing as solved. You can re-open if needed.
