### ISSUE TITLE
Disable Login option

### ISSUE THREAD

**Issue by AmitPr** [mikecao/umami#948]
Hi,
I'm running umami behind a reverse proxy + SSO solution, (traefik + authelia), and I was wondering whether I can disable the login prompt for the admin account. I already make sure that the only unauthorized calls are to `/umami.js` and `/api/collect`. (Or `/api` in general, if we can disable the login prompt for the web interface but keep the API protected)

If there's any way to do this already within umami, I'd appreciate the knowledge, otherwise I may try implementing this as an environment option in a PR.

**Comment by mikecao** [comment]
Going to add an environment variable to allow this.

**Comment by pxlfrk** [comment]
Hi, I am facing the same use case as above. However, the inserted environment variable disables the login flow completely, so that a login via the web UI is no longer possible.

I would welcome an additional environment variable that would allow the entire UI to work without authentication - since it is also secured by an SSO provider (authentik) + reverse proxy (NPM) for me anyway.

PS: I also noticed that the DISABLE_LOGIN variable appears twice on the [environment variables](https://umami.is/docs/environment-variables) page - probably a duplicate.

**Comment by ClearSeve** [comment]
Can we now use authentik instead of the login function?
