### ISSUE TITLE
Public docker image

### ISSUE THREAD

**Issue by Paxa** [mikecao/umami#96]
Is there any public docker image?

**Comment by mikecao** [comment]
I just did a release and it looks like it built the docker images correctly.

https://github.com/mikecao/umami/packages/384661/versions

I am not that familiar with Github actions and packages. Maybe @hugomd can answer how we make images public.

**Comment by hugomd** [comment]
You should be able to pull the Docker image that @mikecao linked above, but you'll have to authenticate with a personal access token. This [help article](https://docs.github.com/en/packages/using-github-packages-with-your-projects-ecosystem/configuring-docker-for-use-with-github-packages#authenticating-to-github-packages) explains it.

This is fine in production environments because you can setup credentials pretty easily, but for individual users pulling it's not ideal. I can raise a PR to also push images to Docker Hub instead, where they'd be accessible anonymously.

That said, [GitHub just announced GitHub Container Registry](https://github.blog/2020-09-01-introducing-github-container-registry/), which will allow users to pull images anonymously. It looks like it's only available for organisations for now though 🤔

**Comment by hugomd** [comment]
> It looks like it's only available for organisations for now though 🤔

I've just tested it and have managed to publish a test (of another repository, not Umami) package here: https://github.com/users/hugomd/packages/container/test/31201

I'll do some more exploring over the weekend to see if we can publish with a `GITHUB_TOKEN` or whether you need a personal access token. This might be a neat fix!

**Comment by hugomd** [comment]
@mikecao @Paxa I've raised a pull request to push to GitHub container registry: #108 

If you want to take it for a spin, you can try using one of these images:
```bash
docker pull ghcr.io/hugomd/umami:mysql-latest
docker pull ghcr.io/hugomd/umami:postgresql-latest
```

Let me know what you think! 🙌🏻

**Comment by Paxa** [comment]
@mikecao Did you consider to enable automated builds with docker hub? It will re-build image on every push to master
https://docs.docker.com/docker-hub/builds/
